name: reusable_testing

on:
  workflow_call:
    inputs:
      artifact_name:
        description: The name of the tarantool build artifact
        default: ubuntu-focal
        required: false
        type: string

jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone the memcached module
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository_owner }}/memcached
          # Enable recursive submodules checkout as test-run git module is used
          # for running tests.
          submodules: recursive

      - name: Download the tarantool build artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.artifact_name }}

      - name: Install tarantool
        # Now we're lucky: all dependencies are already installed. Check package
        # dependencies when migrating to other OS version.
        run: sudo dpkg -i tarantool_*.deb tarantool-common_*.deb tarantool-dev_*.deb

      # TODO: Remove this when https://github.com/tarantool/memcached/issues/96
      # is resolved.
      - name: Get the tarantool version
        run: |
          TNT_VERSION=$(tarantool --version | grep -e '^Tarantool')
          echo "TNT_VERSION=$TNT_VERSION" >> $GITHUB_ENV

      - name: Setup python2 for tests
        uses: actions/setup-python@v2
        with:
          python-version: 2.7

      - name: Install build requirements
        run: sudo apt-get -y install libsasl2-dev

      - name: Install test requirements
        run: pip install -r test-run/requirements.txt

      - run: cmake . && make
      - run: make test-memcached
        # TODO: Remove this when https://github.com/tarantool/memcached/issues/96
        # is resolved.
        if: ${{ startsWith(env.TNT_VERSION, 'Tarantool 1.10') ||
          startsWith(env.TNT_VERSION, 'Tarantool 2.8') }}
